### PR TITLE
Adding interval flag for setting amount of the times to rerun jobs

### PR DESCRIPTION
**Pull request by ErfanMomeniii**
Hi, 
Merging this pull request can rerun jobs in a particular interval of time.
If you have any ideas or concerns regarding the PR, feel free to tell me.

### CODE REVIEW

**Comment by liweiyi88** [comment]
Hi @ErfanMomeniii , 
May I ask if you have some valid use cases to embed cron-like features into this tool while ppl can use tools like crontab, k8s cronjob or Airplane schedules to re-run the tool periodically?

**Comment by ErfanMomeniii** [comment]
I think this feature offers the advantage of eliminating the need for additional tools or concepts to be periodically re-run, thereby providing users with a convenient and optional solution.

**Comment by liweiyi88** [comment]
I am not convinced that it is practical to embed cron-like feature in onedump for prod operations. The main concern is that ppl will still need the external app to recover from the failure of running onedump (e.g. when OOM happened and onedump just crashed)

But I understand that there might be use cases ppl would like to experiment this tool and run it as cron job without external configuration.

Having said that, if we would like to support cron-like feature, lets do it in that way. My suggestion is to use package like https://github.com/jasonlvhit/gocron to support the cron configuration. 🙏

**Comment by liweiyi88** [comment]
@ErfanMomeniii thanks so much for your contribution. Just 2 suggestion in order to merge the PR.
1. It seems that the `https://github.com/jasonlvhit/gocron` project has been moved to `https://github.com/go-co-op/gocron` according to the README file, could we update the dependency and follow the latest practice?
2. In order to have a bit better user experience, I would suggest renaming the `interval` flag to `cron` to allow users to pass something like `--cron 5m`, Also allow users to pass a valid cron expression like `--cron */1 * * * * *` (which I saw the latest package support then out of the box, but you probably need to add logic to distinguish a valid cron expression or a normal string expression). I am not too sure if two options like `--every 5m` and `--cron */1 * * * * *` make more sense than a single `--cron` option at the moment.
Let me know if you are not interested in making those changes, then I will merge your PR and implement the changes myself.

**Comment by ErfanMomeniii** [comment]
I changed the interval flag to `--cron` and used the new package instead of the previous one to add a cron job.

**Comment by liweiyi88** [comment]
@ErfanMomeniii , nice work and thanks you 🎉

**Comment by liweiyi88** [comment]
@ErfanMomeniii btw, could you fix the pipeline error when you get a chance?

**Comment by ErfanMomeniii** [comment]
@liweiyi88, it should be fixed now.

**Comment by liweiyi88** [comment]
I have also put a few minor comments in the PR

**Comment by ErfanMomeniii** [comment]
I'll add some tests for increasing test coverage for each part of the project and notify you for checking that.
Thanks

**Comment by liweiyi88** [comment]
Thank you @ErfanMomeniii

**Pull request merged**
